name: tower_building
description: "Tower Building - stack blocks and build the tallest tower!"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.37.0
  flame_forge2d: ^0.19.2+6
  video_player: ^2.11.1
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.webp
    - assets/logo_name.webp
    - assets/gameplay_assets/
    - assets/additional_assets/loading_screen/
    - assets/music/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.webp"
  remove_alpha_ios: true
  background_color_ios: "#87CEEB"
  adaptive_icon_background: "#87CEEB"
  adaptive_icon_foreground: "assets/logo.webp"
